#! /usr/bin/env bash
set -e

# Script for mounting rclone
#
# With "e" refering to an encrypted drive and "g" to a non encrypted.

case $1 in
	"-e"|"e") sudo rclone mount \
	  	--config=/root/.config/rclone/rclone.conf \
	  	--allow-other \
	  	--vfs-cache-mode=full \
	  	--vfs-cache-max-size=1000M \
	  	--daemon \
	  	edrive: /mnt
		exit 0 ;;
	"-ero"|"ero"|"-roe"|"roe" ) sudo rclone mount \
	  	--config=/root/.config/rclone/rclone.conf \
	  	--allow-other \
	  	--vfs-cache-mode=full \
	  	--vfs-cache-max-size=1000M \
	  	--daemon \
		--read-only \
	  	edrive: /mnt
		exit 0 ;;
	"-ro"|"ro") sudo rclone mount \
	  	--config=/root/.config/rclone/rclone.conf \
	  	--allow-other \
	  	--vfs-cache-mode=full \
	  	--vfs-cache-max-size=1000M \
	  	--daemon \
		--read-only \
	  	gdrive: /mnt
		exit 0 ;;
	"c"|"-c"|"u"|"-u") sudo fusermount -u /mnt ;;
	"") 	sudo rclone mount \
	  	--config=/root/.config/rclone/rclone.conf \
	  	--allow-other \
	  	--vfs-cache-mode=full \
	  	--vfs-cache-max-size=1000M \
	  	--daemon \
	  	gdrive: /mnt
		exit 0 ;;
esac

