#! /usr/bin/env bash

# Script that updates a desktop, with apt, dnf or pacman and also flatpak.

## Common package manager
if [ -x "$(command -v apt)" ];       then echo " --- Upgrading with apt" && sudo apt update && sudo apt upgrade && sudo apt autoremove
elif [ -x "$(command -v dnf)" ];     then echo " --- Upgrading with dnf" && sudo dnf update
elif [ -x "$(command -v pacman)" ];  then echo " --- Upgrading with pacman" && sudo pacman -Syu
else echo "Failed to identy package manager :(, upgrade by yourself"; fi

## If having flatpak
[ -x "$(command -v flatpak)" ] && echo " --- Upgrading flatpak" && flatpak --user update && sudo flatpak update


echo " --- Done ;)"

