#! /usr/bin/env bash

# Script that updates a desktop, with apt, dnf(and rpm-ostree) or pacman, also flatpak and toolbox.

## Common package manager
if [ -x "$(command -v apt)" ];       then echo " --- Upgrading with apt" && sudo apt update && sudo apt upgrade && sudo apt autoremove
elif [ -x "$(command -v dnf)" ];     then echo " --- Upgrading with dnf" && sudo dnf update
elif [ -x "$(command -v rpm-ostree)" ];     then echo " --- Upgrading with rpm-ostree" && rpm-ostree upgrade
elif [ -x "$(command -v pacman)" ];  then echo " --- Upgrading with pacman" && sudo pacman -Syu
else echo "Failed to identy package manager :(, upgrade by yourself"; fi

## If having flatpak
[ -x "$(command -v flatpak)" ] && echo " --- Upgrading flatpak" && flatpak --user update && sudo flatpak update

## If having toolbox (It uses dnf because toolbox is mainly used with fedora)
[ -x "$(command -v toolbox)" ] && echo " --- Upgrading main toolbox" && toolbox run sudo dnf upgrade


echo " --- Done ;)"

