#! /usr/bin/env bash

set -e

# If VAR1 is --help, -h or -?, echo short help text and exit
VAR0=$(basename "$0")
if [ "$1" = "--help" ] || [ "$1" = "-help" ] || [ "$1" = "-h" ] || [ "$1" = "-?" ]; then
    echo "Script for adding everything and pushing to a external git repositorie."
    echo 
    echo "	Format: '$VAR0 The comment for the commit'"
    exit 1
fi

if [ -z "$1" ]; then
    echo "You are mising the comment"
    exit 1
fi

for i in "$*"
	do 
	_all="${_all} $i"
done

git add --all
git commit -m "$_all"
git push -u origin main
