#! /usr/bin/env bash

# Script for adding everything and pushing to a external git repositorie.

set -e

if [ -z "$1" ]; then
    echo "You are mising the comment"
    exit 1
fi

for i in "$*"
	do 
	_all="${_all} $i"
done

git add --all
git commit -m "$_all"
git push -u origin main
