#! /usr/bin/env bash
set -e

# Script for removing title metadata from video files.

# If $1 is empty, --help, -h or -?, echo short help text and exit
VAR0=$(basename "$0")
if [ -z "$1" ] || [ "$1" = "--help" ] || [ "$1" = "-help" ] || [ "$1" = "-h" ] || [ "$1" = "-?" ]; then
    echo "Script for removing metadata from a video file."
    echo 
    echo "For removing metadata from a video file, run:"
    echo "	Format: '$VAR0 file'"
    echo 
    exit 1
fi

if ! [ -f "$1" ]; then
    echo " $1 is not a file"
    exit 1
fi

# Get file name and extension
file_name="$1"
file_extension="${file_name##*.}"

# Change name for working file
tmp_name=$(echo "${file_name}.undone.${file_extension}")
mv "$file_name" "$tmp_name"

# Remove metadata
ffmpeg -i "'$tmp_name'" -map_metadata -1 -fflags +bitexact -flags:v +bitexact -flags:a +bitexact -c:v copy -c:a copy -c:s copy -map 0 "'$file_name'"

# Remove tmp file
rm "$tmp_name"
